env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode11.7
      script:
        - set -o pipefail
        - xcodebuild -project Chess.xcodeproj -scheme Chess -sdk iphonesimulator
